Addded nullChecked support for nullable list
smotastic/smartstruct pull request #42
Opened 2021-12-21 08:13 UTC by gopalsabhadiya

I've added nullChecked for nullable list. (Test is failing due to an issue described below).

Generated source is generating:
```
final nullablelisttarget =
        NullableListTarget(source.list!.map((e) => e).toList());
```

It should be

```
final nullablelisttarget =
        NullableListTarget(source.list!.map(fromSubSource).toList());
```

I'm not sure why `matchingMappingListMethods.isNotEmpty` is returning false. 

If you can help me out, I can make changes and push the commit on this PR.
Also, let me know if there are any other changes related to this.

2021-12-21 08:15 UTC, gopalsabhadiya commented on generator/lib/code_builders/assignment_builder.dart
> +                .nullChecked
This has been added to add `!`. Due to this, I had to pub upgrade the dependencies.

2021-12-22 20:59 UTC, smotastic commented
Hey @gopalsabhadiya 
thank you so much for your contribution. I took a look at it, and it looks good so far.
I made a few comments in the review section, if you have any questions feel free to ask. 
I think I also found your problem with the failing test, see the review

2021-12-23 09:21 UTC, gopalsabhadiya commented
Hi @smotastic 

I failed to find any review comments. Can you please refer me the link to that?

2021-12-23 19:28 UTC, smotastic requested changes

2021-12-23 19:29 UTC, smotastic commented
Hi @gopalsabhadiya 
Yes, sorry. I forgot to click the "request changes" button. Should be there now above my comment

2022-08-12 13:51 UTC, smotastic commented
Hi, I will close this PR for now due to inactivity.
But feel free to open another PR whenever you find the time.

2022-08-12 13:51 UTC, closed without merging