feat: static_proxy.
smotastic/smartstruct pull request #59
Opened 2022-08-21 11:08 UTC by skykaka

Generate static proxy for mapper class for the user can use the mapper without the mapper object.

Which is discussed at https://github.com/smotastic/smartstruct/pull/57#discussion_r901207690.

2022-08-23 19:15 UTC, smotastic commented
Hi @skykaka 
Thank you for the contribution, 
As discussed I like the idea, so I'll make sure to check it out on the weekend

2022-09-02 07:20 UTC, skykaka commented
Hi @smotastic 
The code is not reviewed.  Have you been busy recently, or is there some problem?

2022-09-04 07:40 UTC, smotastic requested changes
Hey, sorry I couldn't check the changes out last week. As you assumed I was very busy. But I like the change overall, just one small suggestion in the code.

2022-09-04 07:40 UTC, smotastic commented on smartstruct/lib/src/annotations.dart
> +  final bool static;
Hey, only thing I'd like to discuss is the name of the configuration. Everything else looks good.
Maybe something like ``generateStaticProxy``?

2022-09-04 13:44 UTC, skykaka commented
Very import suggestion. The name "static" is so arbitrary. I haven't thought enough about this. The name  'generateStaticProxy' is good enough. It's very clear. I think we'd better use this name. I will finish the modification of the code in the next few days.

2022-09-05 15:02 UTC, smotastic approved these changes

2022-09-05 15:02 UTC, merged